### ISSUE TITLE
Implement builtin0-4

### ISSUE THREAD

**Issue by christophwille** [christophwille/dotnet-opa-wasm#3]
Currently only added to satisfy imports, actually properly implement it. Needed: sample rego.

**Comment by christophwille** [comment]
Tracking https://github.com/open-policy-agent/npm-opa-wasm/issues/7

**Comment by christophwille** [comment]
Tracking https://github.com/open-policy-agent/opa/issues/3083

**Comment by iinuwa** [comment]
@christophwille, I played around this weekend and was able to [copy what the NPM SDK is doing for automated tests](https://github.com/iinuwa/dotnet-opa-wasm/tree/add-builtin-tests). Should I open a PR?

I've made it so you can basically copy the exact same YAML test files into a directory in this repo, and NUnit should pick them up and display them as separate tests. I was able to get NUnit to run the tests, but discovery is not working for those tests in VS Code Intellisense, but it does work in the Test Explorer and using `dotnet test`.

I also implemented a few builtin calls as an example ([regex](https://github.com/iinuwa/dotnet-opa-wasm/tree/implement-regex-builtins), [sprintf](https://github.com/iinuwa/dotnet-opa-wasm/tree/implement-string-builtins)). I think that the way it's set up now, to implement new builtins wouldn't require changes to the core OpaPolicy class. An example workflow for contributing a new builtin would be:
1. Copy the corresponding test from open-policy-agent/opa.
2. Implement a normal C# static function in a `Builtins` class (with normal type signatures, etc.).
3. Annotate your function name with `[OpaBuiltin(<name of builtin>)]`.
4. Run the tests to see if they pass.
5. Update the `capabilities.json` file to include the new function.

I know this is a lot of code and changes, so I'm OK if you don't want to pull them in or review them. I just had fun trying it out!

**Comment by iinuwa** [comment]
> I haven't thought about implementation details for builtins, but I had lambdas in mind initially (not really having thought about alternatives or ramifications of certain choices).

Yeah, I didn't think too deeply about it either. I think my main goal was to centralize the value lookups and type casting from OPA/WASM so that the methods had normal type signatures (and could be tested independently). At first, I tried registering `Func` in a Dictionary, but the type signatures became to unwieldy for me to unravel. Someone with more experience might have a different way of going about it.

I'm not sure of the performance impact of using reflection either. I cached the attribute lookup into a static Dictionary, but that's the optimization I made (and I don't even know if that would make a real difference with the JIT). There's also some extra boxing happening between JSON deserialization, and then type-casting to call the builtin implementation method. I haven't benchmarked the builtin calls at all either.

> I'll have a look at your code wrt builtins later this week.

Sounds good. Let me know if opening a PR would make it easier for you to review.

**Comment by christophwille** [comment]
What would be helpful is a couple simple regos to use for unit tests in the inner loop to prototype a few approaches.

**Comment by christophwille** [comment]
Dumping ground for my notes:

The docs: https://www.openpolicyagent.org/docs/latest/wasm/#built-in-functions

The JS impl: https://github.com/open-policy-agent/npm-opa-wasm/blob/7f3b0e0f088222aab279f255b95b8b3919a81a3a/src/opa.js#L97

iinuwa commit: https://github.com/iinuwa/dotnet-opa-wasm/commit/d8435d1e65fc44c41dce1198ecd133ad8382b079

I see the following requirements:

* the caller of this library will define the built-in functions, yes, we might supply a couple "default ones", but in general this will be a per-policy thing. 
* given that it is a per-policy thing, willy-nilly collecting "everything we find" (by whatever means, eg attribute) isn't a good approach

A couple personal guesstimates:

* passing arg1.. arg3 as json strings should be enough. I'd expect most devs to pass a JSON obj as arg1 anyways.

My preference then would be for the built-ins to be an optional argument to eg the ctor. Or a .WithBuiltin composable call.

policy.WithBuiltin(...).WithBuiltin();

additionally we could considers an .WithBuiltins(...) call that takes a hashtable of sorts. Preference: Action<T>

**Comment by christophwille** [comment]
@srenatus is there any more docs on the architectural intentions of wasm builtins other than https://www.openpolicyagent.org/docs/latest/wasm/#built-in-functions ? Thanks. Especially useful would be the "intended use case" eg are builtins a library feature or a per-policy custom feature? The JS code looks like "hard-coded and library-provided" whereas the wasm docs seem to suggest that any policy can come with any custom builtin requirement.

**Comment by srenatus** [comment]
The set of SDK-provided built-ins that a module needs depends on the rego code. So, if your policy only makes use of natively-implemented functions ([the "✅" rows here](https://www.openpolicyagent.org/docs/latest/policy-reference/#built-in-functions)), then it will not need any of the SDK-provided built-in functions. Also, the builtins will only be required if the policy evaluation actually takes a path that requires the built-in, e.g.

```rego
package foo

allow {
  input.x == "bar"
  http.send({...})
}
```
would never call the built-in if input.x wasn't `bar`.
  
When compiling a policy to wasm, there's a capabilities file that defines the set of available builtins. When you do `opa build -t wasm`, it'll use the capabilities of the opa binary you're using. You could, for example, have a capabilities file that only declares the natively-implemented built-ins, and if you used that for compiling your wasm module, you'd have some assurance: the `opa build` command would fail if the rego policy used a built-in not in the capabilities file.

Similarly, you could maintain a capabilities file that covers the natively-implemented functions PLUS the ones implemented in this specific SDK -- it could then be used for compiling rego to wasm _meant for the use with this SDK_, and you'd know at build time that it's going to work in the end.

To make life colourful, your capabilities file used with `opa build` could declare built-in functions that opa doesn't know at all, but you could provide them in your SDK. Anything you could come up with, really.

The short answer is
> any policy can come with any custom builtin requirement

but you can control it using the capabilities feature.

**Comment by christophwille** [comment]
Thanks for the detailed answer! Regarding the "SDK-dependent" piece re:functions more generally: Is there a page / md somewhere on the common features SDKs are supposed to support? Like "at the minimum an SDK must support a, b, c..." or "a full-on SDK must additionally provide the following x, y, z".

**Comment by christophwille** [comment]
I'd like to harken back to the capabilities file... scenario "one additional custom function whatever.func". What is the easiest way to tell opa build that I want "all the stuff that OPA comes with + my custom func". Because I only see --capabilities taking one file. And copy/pasting the default file to append one custom single capability seems a lot of work (esp. when OPA revs, I'd need to keep my copy updated with the new "defaults")

**Comment by srenatus** [comment]
There is no simpler way right now. But I suppose the addition of a single function could be automated, via a clever `opa eval` or jq call 🤔

**Comment by iinuwa** [comment]
>  Is there a page / md somewhere on the common features SDKs are supposed to support? ...
> Nope there's no such guidance, I'm afraid.

Maybe in place of this, repositories of rego files ([example](https://github.com/anderseknert/awesome-opa#policy-packages)) could be scraped and parsed to see which builtins are called the most to determine the implementation priority. I would imagine that `http.send`, and SDK-dependent `regex` builtins would be pretty high on the list.

> And copy/pasting the default file to append one custom single capability seems a lot of work (esp. when OPA revs, I'd need to keep my copy updated with the new "defaults")

I totally agree; it was a pain to do that in the patch that I made. That would also keep you locked into the latest version of OPA. (Otherwise users may naively write and build policies based on functions that the SDK doesn't provide.)

Off-topic for this repo, but maybe a feature could be added to `opa build` to create a new `--add-capabilities` flag that can be specified multiple times with different JSON files. Its behavior could be:
- to add new capabilities _on top of the provided ones_, in other words, the non-SDK-dependent builtins would be retained
- and to merge the given files by:
  - producing union of the `allow_net` arrays 
  - merging `builtins` by `builtins.name`, failing if there are any builtins that are specified twice.

Then the SDK authors could just write the capabilities that they explicitly provide, and SDK users could append to that with their own custom functions.

Until then, maybe maintaining a capabilities.json file with instructions to copy the [default capabilties from the open-policy-agent/opa repo](https://github.com/open-policy-agent/opa/tree/main/capabilities) and merge the SDK capabilities using `jq` as `srenatus` mentioned would be better. More work for the user, but more maintainable.

**Comment by iinuwa** [comment]
Here's a shell script that can merge capabilities files, optionally overwriting builtins that are defined more than once.

It's written in `sh`, so it'd require Git Bash/Cygwin/WSL to run on Windows, but I can port it to PowerShell Core if that's more desirable.

<details>
<summary>merge-capabilities.sh</summary>

```sh
#!/usr/bin/env sh

HELP="A utility to merge Open Policy Agent capabilites.json files.

Usage:
    $0 [--allow-duplicate-builtins] <FILE>...

Options:
    --allow-duplicate-builtins
            Allows builtin functions to be defined multiple times. The last
            definition specified, based on the order of the <FILE> parameters,
            will be included in the output.
    -h, --help
           Print this help.

Arguments:
    <FILE>...
      File(s) to merge. Use a dash ('-') to read from standard input.

Examples:
    # Add custom policies to delivered policies
    $0 capabilities-v0.34.0.json capabilities-custom.json

    # Add a remote host definition
    echo '{\"allow_net\": [\"example.com\"]}' | $0 capabilities-v0.34.0.json -

You can find the delivered capabilities files for each OPA version online[0].

See the capabilities documentation[1] for more information.

[0]: https://github.com/open-policy-agent/opa/tree/main/capabilities
[1]: https://www.openpolicyagent.org/docs/latest/deployments/#capabilities
"

for arg in $@; do
  if [ "--help" = "$arg" ] || [ "-h" = "$arg" ]; then
    echo "$HELP"
    exit 0
  fi
done

if [ -p /dev/stdin ]; then
  read STDIN
  STDIN=$(echo -n $STDIN | jq '$default * .' --argjson default '{ "allow_net": [],"builtins": [] }')
fi

FILES=$@
DUPLICATED_BUILTINS=$(echo -n "$STDIN" | jq -s -r '
  [ .[].builtins | .[] ]
  | group_by(.name)
  | map(select(length > 1))
  | map((.[0].name))
  | join(" ,")
  ' $FILES)

if [ ! -z "$DUPLICATED_BUILTINS" ]; then
  echo "Duplicated builtins defined: $DUPLICATED_BUILTINS"
  echo "Exiting."
  exit 1
fi

echo -n "$STDIN" | jq -s '
  {
    allow_net: [
      .[]
      | .allow_net[]
    ] | unique,

    builtins:
      [ .[].builtins | .[]]
      | group_by(.name)
      | map(.[-1])
  }' $FILES
```

</details>
